name: Kotlin CI with Gradle

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew 1
      working-directory: task4-1-1-MaxCoverage
      run: chmod +x gradlew
    - name: Build with Gradle 1
      working-directory: task4-1-1-MaxCoverage
      run: ./gradlew build --info
    - name: Grant execute permission for gradlew 2
      working-directory: task5-1-PostsWallTests
      run: chmod +x gradlew
    - name: Build with Gradle 2
      working-directory: task5-1-PostsWallTests
      run: ./gradlew build --info
